/**
 * api.files.testFilesIntegration — the files integration test on the API
 * surface (10b-files slice API-TEST, #39). Gateway route:
 * `POST /{version}/files/{filesIntegrationId}/test`.
 *
 * Hand-written, in its own file: `tests/api/files.test.ts` is regenerated by
 * `npm run generate-endpoints` and would lose these (same rule slice SDK-2
 * followed for tests/files-public.test.ts).
 *
 * Every test runs against a fake fetch — never a real server.
 */
import { describe, expect, it } from 'vitest';

import { NorbixAuthError, NorbixError } from '../../src/index.js';
import type { CodeMashApi2 } from '../../src/types/api2.dtos.js';
import { createMockFetch, makeClient } from '../_helpers.js';

/** The body the gateway answers when the four probe steps all worked. */
const HAPPY_BODY = {
  items: [
    { operation: 'UploadFile', result: 'OK' },
    { operation: 'GetFile', result: 'OK' },
    { operation: 'GetAllFiles', result: 'OK' },
    { operation: 'DeleteFile', result: 'OK' },
  ],
  responseStatus: { isSuccess: true },
};

function clientAnswering(opts: { status?: number; body?: unknown }) {
  const mock = createMockFetch(opts);
  const { norbix } = makeClient({ fetch: mock.fetch });
  return { norbix, mock };
}

describe('api.files.testFilesIntegration', () => {
  it('is a method on the API client (not only on the Hub client)', () => {
    const { norbix } = makeClient();
    expect(typeof norbix.api.files.testFilesIntegration).toBe('function');
    // The Hub one is a different endpoint and stays as it was.
    expect(typeof norbix.hub.files.testFilesIntegration).toBe('function');
    expect(norbix.api.files.testFilesIntegration).not.toBe(norbix.hub.files.testFilesIntegration);
  });

  it('sends POST /v2/files/<id>/test with the id in the path, not in the body', async () => {
    const { norbix, mock } = clientAnswering({ body: HAPPY_BODY });

    await norbix.api.files.testFilesIntegration({ filesIntegrationId: 'int_42' });

    expect(mock.calls).toHaveLength(1);
    const call = mock.lastCall!;
    expect(call.method).toBe('POST');
    expect(call.url).toBe('https://api.norbix.io/v2/files/int_42/test');
    // The id is consumed by the path; nothing else was given, so no body.
    expect(call.body).toBeUndefined();
  });

  it('escapes the id like every other path token', async () => {
    const { norbix, mock } = clientAnswering({ body: HAPPY_BODY });

    await norbix.api.files.testFilesIntegration({ filesIntegrationId: 'a b/c' });

    expect(mock.lastCall!.url).toBe('https://api.norbix.io/v2/files/a%20b%2Fc/test');
  });

  it('sends the project scope and the session like its neighbours', async () => {
    const { norbix, mock } = clientAnswering({ body: HAPPY_BODY });

    await norbix.api.files.testFilesIntegration({ filesIntegrationId: 'int_42' });

    const h = mock.lastCall!.headers;
    expect(h.get('Authorization')).toBe('Bearer test-token');
    expect(h.get('norbix-project-id')).toBe('test-project');
    expect(h.get('X-CM-ProjectId')).toBe('test-project');
  });

  it('gives back the probe items parsed, one per step', async () => {
    const { norbix } = clientAnswering({ body: HAPPY_BODY });

    const res: CodeMashApi2.TestFilesIntegrationResponse =
      await norbix.api.files.testFilesIntegration({ filesIntegrationId: 'int_42' });

    expect(res.responseStatus.isSuccess).toBe(true);
    expect(res.items?.map((i) => i.operation)).toEqual([
      'UploadFile',
      'GetFile',
      'GetAllFiles',
      'DeleteFile',
    ]);
    expect(res.items?.every((i) => i.result === 'OK')).toBe(true);
  });

  it('keeps the errors of a failed step and the steps it skipped', async () => {
    const { norbix } = clientAnswering({
      body: {
        items: [
          { operation: 'UploadFile', result: 'FAILED', errors: ['Access denied by the bucket'] },
          { operation: 'GetFile', result: 'NOT_TESTED' },
          { operation: 'GetAllFiles', result: 'NOT_TESTED' },
          { operation: 'DeleteFile', result: 'NOT_TESTED' },
        ],
        responseStatus: { isSuccess: true },
      },
    });

    const res = await norbix.api.files.testFilesIntegration({ filesIntegrationId: 'int_42' });

    expect(res.items?.[0]).toEqual({
      operation: 'UploadFile',
      result: 'FAILED',
      errors: ['Access denied by the bucket'],
    });
    expect(res.items?.slice(1).map((i) => i.result)).toEqual([
      'NOT_TESTED',
      'NOT_TESTED',
      'NOT_TESTED',
    ]);
  });

  it('an error status with a ResponseStatus body throws the usual NorbixError', async () => {
    const { norbix } = clientAnswering({
      status: 403,
      body: {
        responseStatus: {
          errorCode: 'Forbidden',
          message: 'Missing permission files:create',
        },
      },
    });

    const call = norbix.api.files.testFilesIntegration({ filesIntegrationId: 'int_42' });

    await expect(call).rejects.toBeInstanceOf(NorbixAuthError);
    await expect(call).rejects.toMatchObject({
      status: 403,
      code: 'Forbidden',
      message: 'Missing permission files:create',
    });
  });

  /**
   * Pins today's behaviour of the whole SDK, not only of this method: the
   * transport throws on a non-2xx status only. A gateway error answered with
   * `200` and `responseStatus.isSuccess = false` (how the gateway's own
   * service tests show "unknown integration") comes back as a value.
   */
  it('a 200 with isSuccess=false comes back as a value, errors readable', async () => {
    const { norbix } = clientAnswering({
      body: {
        responseStatus: {
          isSuccess: false,
          errors: [
            {
              message: 'Integration with id int_42 not found',
              errorCode: 'CM-ERRORS-INTEGRATIONS-001',
            },
          ],
        },
      },
    });

    const res = await norbix.api.files.testFilesIntegration({ filesIntegrationId: 'int_42' });

    expect(res.items).toBeUndefined();
    expect(res.responseStatus.isSuccess).toBe(false);
    expect(res.responseStatus.errors?.[0]?.errorCode).toBe('CM-ERRORS-INTEGRATIONS-001');
  });

  it('a 404 is a NorbixError with the status (POST is never retried)', async () => {
    const { norbix, mock } = clientAnswering({ status: 404, body: {} });

    await expect(
      norbix.api.files.testFilesIntegration({ filesIntegrationId: 'int_42' }),
    ).rejects.toBeInstanceOf(NorbixError);
    expect(mock.calls).toHaveLength(1);
  });

  it('refuses to build the URL without an integration id', async () => {
    const { norbix, mock } = clientAnswering({ body: HAPPY_BODY });

    await expect(norbix.api.files.testFilesIntegration({})).rejects.toMatchObject({
      code: 'NORBIX_MISSING_PATH_PARAM',
    });
    expect(mock.calls).toHaveLength(0);
  });
});
